language: groovy
jdk:
  - oraclejdk7
sudo: false
branches:
  only:
    - dev
    - master
    - hotfix
    - grails3
cache:
  directories:
    - ~/.m2/repository
    - ~/.grails/wrapper
before_install:
  - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
  - chmod +x ala_common.sh
  - source ./ala_common.sh
  - ala_travis_grails_repo_setup
script:
  - ala_travis_grails_test
after_success:
  - ala_travis_grails_deploy
env:
  global:
  - secure: SXv/tzFEVilHYotkGZG7wSRM5fNSJmNaZX2x9o+AgLSZWFk2ZEqkgYP5utIMURghO+XW1i6GSBjpopcTttMvGC3+m5B6LLrmgSMiLRmzji34XfKpLysY3U7nU24F6aRDf+HvmyLtuj/tOXG+aD9odMjJ2rOONEEri6UcIP7bSOg=
  - secure: bulQ1yxzUFsM/VO/B/AM6WLRQ0ni+UJbEGKuxRB/3GfEHAnY5NLYX60t1gZY1Mv8Rg0t0/dRttniw7dVytvuIYMbI+gsY+eq6FTSgRjUUP3Y0hJd4B6JKnEQWPzR10s8HLiWdYIBUx3jL66kUhfQavgFjRnJKQ4Ql8pgSmez/9k=
